version: "2.3"
services:
  demo-container-db:
    image: postgres:12
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    expose:
    - "5432"
    volumes:
    - db-data:/var/lib/postgresql/data1
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass hello
    ports:
    - "6379:6379"
    expose:
    - "6379"
    volumes:
    - /tmp/redis-data:/var/lib/redis
    - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
    - REDIS_REPLICATION_MODE=master

volumes:
  db-data:
