version: "2.3"
services:
  demo-container-db:
    image: postgres:12
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    expose:
    - "5432"
    volumes:
    - db-data:/var/lib/postgresql/data1

volumes:
  db-data:
